addr = "127.0.0.1:9527"
## Retrieve authentication information from the Docker configuration file if the username and password are not specified.
# docker_config_file = "${HOME}/.docker/config.json"

# if the field in rule is empty, use the value in base_rule.
[base_rule]
mirror_registry = "mirror-registry"
## Available parameters in template: {{.raw}} {{.mirror}}
## {{.Raw.Registry}} {{.Raw.Alias}} {{.Raw.Project}} {{.Raw.Repo}} {{.Raw.Tag}}
## {{.Mirror.Registry}} {{.Mirror.Alias}} {{.Mirror.Project}} {{.Mirror.Repo}} {{.Mirror.Tag}}
path_tpl = "{{.Registry}}/{{.Project}}-{{.Repo}}:{{.Tag}}"
## The cmd will be executed when the image is not found in the mirror registry.
# on_missing_tpl = """
# ssh <PROXY_SERVER> -- \
#   'docker pull {{.raw}} && docker tag {{.raw}} {{.mirror}} && docker push {{.mirror}}'
# """

[registry."<local-registry>:5000"]
alias = "mirror-registry"
# user = "my_username_1"
# password = "my_password_1"

[rule."docker.io"]
[rule."gcr.io"]
[rule."ghcr.io"]
[rule."k8s.gcr.io"]
[rule."registry.k8s.io"]
[rule."quay.io"]
[rule."nvcr.io"]
